module FizzBuzzFunctionsTests 

open NUnit.Framework
open FizzBuzzKata.FizzBuzzFunctions

type IntegerAndFizzBuzzValue = {
                                Value: int
                                Output: string
                            }
let IntegerAndFizzBuzzValue v o = {
                                Value = v
                                Output = o
                                }

let integerAndFizzBuzzValues =
    seq {
        yield IntegerAndFizzBuzzValue 1 "1"
        yield IntegerAndFizzBuzzValue 2 "2"
        yield IntegerAndFizzBuzzValue 3 "Fizz"
        yield IntegerAndFizzBuzzValue 4 "4"
        yield IntegerAndFizzBuzzValue 5 "Buzz"
        yield IntegerAndFizzBuzzValue 6 "Fizz"
        yield IntegerAndFizzBuzzValue 7 "7"
        yield IntegerAndFizzBuzzValue 8 "8"
        yield IntegerAndFizzBuzzValue 9 "Fizz"
        yield IntegerAndFizzBuzzValue 10 "Buzz"
        yield IntegerAndFizzBuzzValue 11 "11"
        yield IntegerAndFizzBuzzValue 12 "Fizz"
        yield IntegerAndFizzBuzzValue 13 "13"
        yield IntegerAndFizzBuzzValue 14 "14"
        yield IntegerAndFizzBuzzValue 15 "FizzBuzz"
        yield IntegerAndFizzBuzzValue 16 "16"
        yield IntegerAndFizzBuzzValue 17 "17"
        yield IntegerAndFizzBuzzValue 18 "Fizz"
        yield IntegerAndFizzBuzzValue 19 "19"
        yield IntegerAndFizzBuzzValue 20 "Buzz"
        yield IntegerAndFizzBuzzValue 21 "Fizz"
        yield IntegerAndFizzBuzzValue 22 "22"
        yield IntegerAndFizzBuzzValue 23 "23"
        yield IntegerAndFizzBuzzValue 24 "Fizz"
        yield IntegerAndFizzBuzzValue 25 "Buzz"
        yield IntegerAndFizzBuzzValue 26 "26"
        yield IntegerAndFizzBuzzValue 27 "Fizz"
        yield IntegerAndFizzBuzzValue 28 "28"
        yield IntegerAndFizzBuzzValue 29 "29"
        yield IntegerAndFizzBuzzValue 30 "FizzBuzz"
        yield IntegerAndFizzBuzzValue 31 "31"
        yield IntegerAndFizzBuzzValue 32 "32"
        yield IntegerAndFizzBuzzValue 33 "Fizz"
        yield IntegerAndFizzBuzzValue 34 "34"
        yield IntegerAndFizzBuzzValue 35 "Buzz"
        yield IntegerAndFizzBuzzValue 36 "Fizz"
        yield IntegerAndFizzBuzzValue 37 "37"
        yield IntegerAndFizzBuzzValue 38 "38"
        yield IntegerAndFizzBuzzValue 39 "Fizz"
        yield IntegerAndFizzBuzzValue 40 "Buzz"
        yield IntegerAndFizzBuzzValue 41 "41"
        yield IntegerAndFizzBuzzValue 42 "Fizz"
        yield IntegerAndFizzBuzzValue 43 "43"
        yield IntegerAndFizzBuzzValue 44 "44"
        yield IntegerAndFizzBuzzValue 45 "FizzBuzz"
        yield IntegerAndFizzBuzzValue 46 "46"
        yield IntegerAndFizzBuzzValue 47 "47"
        yield IntegerAndFizzBuzzValue 48 "Fizz"
        yield IntegerAndFizzBuzzValue 49 "49"
        yield IntegerAndFizzBuzzValue 50 "Buzz"
        yield IntegerAndFizzBuzzValue 51 "Fizz"
        yield IntegerAndFizzBuzzValue 52 "52"
        yield IntegerAndFizzBuzzValue 53 "53"
        yield IntegerAndFizzBuzzValue 54 "Fizz"
        yield IntegerAndFizzBuzzValue 55 "Buzz"
        yield IntegerAndFizzBuzzValue 56 "56"
        yield IntegerAndFizzBuzzValue 57 "Fizz"
        yield IntegerAndFizzBuzzValue 58 "58"
        yield IntegerAndFizzBuzzValue 59 "59"
        yield IntegerAndFizzBuzzValue 60 "FizzBuzz"
        yield IntegerAndFizzBuzzValue 61 "61"
        yield IntegerAndFizzBuzzValue 62 "62"
        yield IntegerAndFizzBuzzValue 63 "Fizz"
        yield IntegerAndFizzBuzzValue 64 "64"
        yield IntegerAndFizzBuzzValue 65 "Buzz"
        yield IntegerAndFizzBuzzValue 66 "Fizz"
        yield IntegerAndFizzBuzzValue 67 "67"
        yield IntegerAndFizzBuzzValue 68 "68"
        yield IntegerAndFizzBuzzValue 69 "Fizz"
        yield IntegerAndFizzBuzzValue 70 "Buzz"
        yield IntegerAndFizzBuzzValue 71 "71"
        yield IntegerAndFizzBuzzValue 72 "Fizz"
        yield IntegerAndFizzBuzzValue 73 "73"
        yield IntegerAndFizzBuzzValue 74 "74"
        yield IntegerAndFizzBuzzValue 75 "FizzBuzz"
        yield IntegerAndFizzBuzzValue 76 "76"
        yield IntegerAndFizzBuzzValue 77 "77"
        yield IntegerAndFizzBuzzValue 78 "Fizz"
        yield IntegerAndFizzBuzzValue 79 "79"
        yield IntegerAndFizzBuzzValue 80 "Buzz"
        yield IntegerAndFizzBuzzValue 81 "Fizz"
        yield IntegerAndFizzBuzzValue 82 "82"
        yield IntegerAndFizzBuzzValue 83 "83"
        yield IntegerAndFizzBuzzValue 84 "Fizz"
        yield IntegerAndFizzBuzzValue 85 "Buzz"
        yield IntegerAndFizzBuzzValue 86 "86"
        yield IntegerAndFizzBuzzValue 87 "Fizz"
        yield IntegerAndFizzBuzzValue 88 "88"
        yield IntegerAndFizzBuzzValue 89 "89"
        yield IntegerAndFizzBuzzValue 90 "FizzBuzz"
        yield IntegerAndFizzBuzzValue 91 "91"
        yield IntegerAndFizzBuzzValue 92 "92"
        yield IntegerAndFizzBuzzValue 93 "Fizz"
        yield IntegerAndFizzBuzzValue 94 "94"
        yield IntegerAndFizzBuzzValue 95 "Buzz"
        yield IntegerAndFizzBuzzValue 96 "Fizz"
        yield IntegerAndFizzBuzzValue 97 "97"
        yield IntegerAndFizzBuzzValue 98 "98"
        yield IntegerAndFizzBuzzValue 99 "Fizz"
        yield IntegerAndFizzBuzzValue 100 "Buzz"
    }

[<TestCaseSource("integerAndFizzBuzzValues")>]
let FizzBuzzOutput_GivenIntegerValue_ReturnsCorrectOutput({Value = v; Output = o}) =
    let returnedValue = FizzBuzz v
    Assert.That(returnedValue,Is.EqualTo(o))